pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - echo "Wow"
  mq:
    image: nsqio/nsq
    detach: true
    commands:
      - /nsqlookupd

services:
  eventstore:
    image: eventstore/eventstore
  database:
    image: mysql

matrix:
  GO_VERSION:
    - 1.7
    - 1.6