pipeline:
  nsqlookupd:
    image: nsqio/nsq
    detach: true
    commands:
      - /nsqlookupd

  nsqd:
    image: nsqio/nsq
    detach: true
    commands:
      - /nsqd --lookupd-tcp-address=127.0.0.1:4160 --broadcast-address=127.0.0.1

  build:
    image: golang:${GO_VERSION}
    environment:
      - GOPATH=/drone
    commands:
      - make deps test
      # - make test_mysql

  #slack:
  #  image: plugins/slack
  #  webhook_url: ${SLACK_TOKEN}
  #  channel: builds
  #  username: drone

#
services:
  eventstore:
    image: eventstore/eventstore

  prometheus:
    image: prom/prometheus

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=service

  consul:
    image: consul

#
matrix:
  GO_VERSION:
    - 1.8
    - 1.7
    - 1.6