pipeline:
  nsqlookupd:
    image: nsqio/nsq
    detach: true
    commands:
      - /nsqlookupd

  nsqd:
    image: nsqio/nsq
    detach: true
    commands:
      - /nsqd --lookupd-tcp-address=127.0.0.1:4160 --broadcast-address=127.0.0.1

  build:
    image: golang:${GO_VERSION}
    environment:
      - GOPATH=/drone
    commands:
      # initialize
      - printf "%s\n------------------------------\n---------  S T A R T ---------\n------------------------------%s\n%s\n"
      - apt update
      - apt install tree
      # tree
      - printf "%s\n------------------------------\n---------   T R E E  ---------\n------------------------------%s\n%s\n"
      - tree -I 'vendor'
      # dependencies
      - printf "%s\n------------------------------\n---------   D E P S  ---------\n------------------------------%s\n%s\n"
      - go get ./...
      # tests
      - printf "%s\n------------------------------\n---------  S T A R T ---------\n------------------------------%s\n%s\n"
      - chmod +x ./test.sh
      - ./test.sh

#
services:
  eventstore:
    image: eventstore/eventstore

  prometheus:
    image: prom/prometheus

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=service

  consul:
    image: consul

#
matrix:
  GO_VERSION:
    - 1.7
    - 1.6