pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - echo "Wow"

services:
  eventstore:
    image: eventstore/eventstore
  database:
    image: mysql
  mq:
    image: nsqio/nsq /nsqlookupd

matrix:
  GO_VERSION:
    - 1.7
    - 1.6