pipeline:
  build:
    image: golang:${GO_VERSION}
    environment:
      - GOPATH=/drone
    commands:
      # initialize
      - apt update
      - apt install tree
      # tree
      - tree -I 'vendor'
      # dependencies, tests
      - go get ./...
      - chmod +x ./test.sh
      - ./test.sh

#
services:
  eventstore:
    image: eventstore/eventstore

  prometheus:
    image: prom/prometheus

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=service

  consul:
    image: consul

  nsqd:
    image: nsqio/nsq
    commands:
      - /nsqd --lookupd-tcp-address=127.0.0.1:4160 --broadcast-address=127.0.0.1

  nsqlookupd:
    image: nsqio/nsq
    commands:
      - /nsqlookupd

#
matrix:
  GO_VERSION:
    - 1.7
    - 1.6